# Generated by Django 6.0.4 on 2026-07-29 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_key', models.CharField(db_index=True, max_length=128)),
                ('business_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('ACTIVATING', 'Activating'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring soon'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed')], default='ISSUED', max_length=24)),
                ('issued_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('policy_version', models.PositiveIntegerField()),
                ('pass_version', models.PositiveIntegerField(default=1)),
                ('network_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wifi_passes', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('EXPIRE_PASS', 'Expire pass'), ('SEND_EXPIRING_NOTIFICATION', 'Send notification'), ('REVOKE_NETWORK_ACCESS', 'Revoke network')], max_length=40)),
                ('execute_at', models.DateTimeField()),
                ('pass_version', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('wifi_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='wifi.wifipass')),
            ],
        ),
        migrations.CreateModel(
            name='PassExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minutes', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('wifi_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='wifi.wifipass')),
            ],
        ),
        migrations.CreateModel(
            name='WiFiPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('base_minutes', models.PositiveIntegerField(default=120)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_until', models.TimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_policies', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='WiFiAmountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('FIRST', 'First order'), ('ADDITIONAL', 'Additional order')], max_length=20)),
                ('min_amount', models.PositiveIntegerField()),
                ('bonus_minutes', models.PositiveIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_tiers', to='wifi.wifipolicy')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AddConstraint(
            model_name='wifipolicy',
            constraint=models.UniqueConstraint(fields=('store', 'version'), name='unique_store_wifi_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='wifiamounttier',
            constraint=models.UniqueConstraint(fields=('policy', 'order_type', 'min_amount'), name='unique_policy_order_type_amount'),
        ),
    ]
