# Generated by Django 6.0.4 on 2026-07-29 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_phone_last4'),
        ('stores', '0002_alter_store_business_day_cutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_key', models.CharField(db_index=True, max_length=128)),
                ('phone_last4', models.CharField(max_length=4)),
                ('code_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'customer_key', 'created_at'], name='identity_ve_store_i_e9b40d_idx'), models.Index(fields=['status', 'expires_at'], name='identity_ve_status_1387d3_idx')],
            },
        ),
    ]
