# Generated by Django 6.0.4 on 2026-07-29 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0002_alter_store_business_day_cutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='EA', max_length=20)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RECEIVED', 'Received'), ('CONSUMED', 'Consumed'), ('ADJUSTED', 'Adjusted'), ('RISK_DETECTED', 'Risk detected'), ('EXPIRED', 'Expired')], max_length=24)),
                ('quantity_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['store', 'expires_on'], name='inventory_i_store_i_1efd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['store', 'risk_score'], name='inventory_i_store_i_48f476_idx'),
        ),
    ]
