# Generated by Django 6.0.4 on 2026-07-29 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('customer_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('AWAITING_CHOICE', 'Awaiting choice'), ('FULFILLED', 'Fulfilled'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='AWAITING_CHOICE', max_length=24)),
                ('fulfill_mode', models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate'), ('COUPON_7D', 'Coupon for seven days')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_grants', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_key', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='AVAILABLE', max_length=20)),
                ('benefit_snapshot', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='stores.store')),
                ('reward_grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='rewards.rewardgrant')),
            ],
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('threshold_amount', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_tiers', to='stores.store')),
            ],
            options={
                'ordering': ['sort_order', 'threshold_amount'],
            },
        ),
        migrations.AddField(
            model_name='rewardgrant',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rewards.rewardtier'),
        ),
        migrations.CreateModel(
            name='RewardTierBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(choices=[('DISCOUNT_COUPON', 'Discount coupon'), ('MILEAGE', 'Mileage'), ('FREE_SHOT', 'Free shot'), ('FREE_SIZE_UP', 'Free size up'), ('DESSERT_DISCOUNT', 'Dessert discount'), ('WIFI_DAY_PASS', 'Wi-Fi day pass'), ('DRINK_DISCOUNT', 'Drink discount'), ('MENU_TRIAL', 'Menu trial')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='rewards.rewardtier')),
            ],
        ),
        migrations.AddField(
            model_name='rewardgrant',
            name='chosen_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards.rewardtierbenefit'),
        ),
        migrations.CreateModel(
            name='DailySpendBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('customer_key', models.CharField(max_length=128)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'business_date', 'customer_key'), name='unique_daily_spend_balance')],
            },
        ),
        migrations.AddConstraint(
            model_name='rewardtier',
            constraint=models.UniqueConstraint(fields=('store', 'threshold_amount'), name='unique_store_reward_threshold'),
        ),
        migrations.AddConstraint(
            model_name='rewardgrant',
            constraint=models.UniqueConstraint(fields=('store', 'business_date', 'customer_key', 'tier'), name='unique_daily_tier_grant'),
        ),
    ]
