# Generated by Django 6.0.4 on 2026-07-29 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_last4'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmediateBenefitRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('APPLIED', 'Applied'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='AVAILABLE', max_length=20)),
                ('benefit_snapshot', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('reward_grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='immediate_redemption', to='rewards.rewardgrant')),
            ],
        ),
    ]
