# Generated by Django 6.0.4 on 2026-07-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0001_initial'),
        ('stores', '0002_alter_store_business_day_cutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField()),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('gross_sales', models.PositiveIntegerField(default=0)),
                ('wifi_active_count', models.PositiveIntegerField(default=0)),
                ('wifi_active_minutes', models.PositiveIntegerField(default=0)),
                ('menu_sales', models.JSONField(default=dict)),
                ('repeat_customer_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_analytics', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'bucket_start'], name='ai_ops_anal_store_i_f6a3fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'bucket_start'), name='unique_store_hourly_bucket')],
            },
        ),
    ]
