# Generated by Django 6.0.4 on 2026-07-29 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_alter_store_business_day_cutoff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('ALIMTALK', 'Alimtalk'), ('IN_APP', 'In-app')], max_length=20)),
                ('template', models.CharField(max_length=80)),
                ('destination_last4', models.CharField(blank=True, max_length=4)),
                ('payload', models.JSONField(default=dict)),
                ('provider', models.CharField(default='DEMO', max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_retention_days', models.PositiveIntegerField(default=30)),
                ('verification_retention_days', models.PositiveIntegerField(default=7)),
                ('audit_retention_days', models.PositiveIntegerField(default=365)),
                ('notice_text', models.TextField(default='전화번호는 Wi-Fi 이용권 연결과 부정 이용 대응을 위해 암호화·해시 처리되며, 매장 정책의 보존 기간 이후 자동 폐기됩니다.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_retention', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'created_at'], name='operations__store_i_7e4995_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'occurred_at'], name='operations__store_i_432128_idx'), models.Index(fields=['published_at', 'occurred_at'], name='operations__publish_8a0317_idx')],
            },
        ),
    ]
