# Generated by Django 6.0.4 on 2026-08-01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(default="SMS", max_length=20)),
                ("destination_last4", models.CharField(blank=True, max_length=4)),
                ("body", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_messages",
                        to="stores.store",
                    ),
                ),
            ],
            options={"db_table": "demo_messages"},
        ),
    ]
