# Generated by Django 6.0.4 on 2026-07-29 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business_day_cutoff',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
