# Generated by Django 6.0.4 on 2026-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_ciphertext',
            field=models.TextField(blank=True),
        ),
    ]
